name: Run SA Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Run Script
        run: |
          wget https://raw.githubusercontent.com/gameswhit/t3rna/main/sa.sh -O sa.sh
          chmod +x sa.sh
          ./sa.sh
